### ISSUE TITLE
Splitter 1x9 clamps values to +-11.7V

### ISSUE THREAD

**Issue by mocmichal** [DomiKamu/Ohmer#2]
I don't know, whether this is desired behavior (to be physically realistic as EuroRack?), but Splitter 1x9 clamps values above 11,7V.
![sg_ohmer_issue_splitter_clamps_values](https://user-images.githubusercontent.com/5244956/64292610-0727a600-cf6b-11e9-9d2b-905db8c2b35f.JPG)

**Comment by DomiKamu** [comment]
Yes it's normal, it follows the realistic Eurorack voltages (12 V, minus 0.3 V fall due to diodes behind power supply).

As confirmed here (Levels paragraph) : https://vcvrack.com/manual/VoltageStandards.html

I close this issue.
